name = "S.U.C.K"
modname = "SUCK"
mainprefix = "p"
prefix = "dcd_suck"
author = "DCD"
sig_version = 3
version = "1.0.06"
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE.md",
    "README.md"
]
include = ["./include"]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip @{{modname}}_{{version}}"
]

# see: https://synixebrett.github.io/HEMTT/#/scripts
# or use ./include to model directory an include mod.cpps
releasebuild = [
  "!build"
]

[scripts.build]
steps_linux = [
    "make linux",
    "cp bin/ release/{{version}}/ -r"
]
steps_windows = [
    "make windows",
    "copy bin/ release/{{version}}/"
]
