name = "S.U.C.K."
prefix = "dcd"
author = "Steffie"
sig_version = 3
version = "1.0.06"
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE.md",
    "README.md"
]
include = ["./include"]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip @SUCK"
]
