name = "Simple UBGL Conversion Kit"
modname = "@SUCK"
prefix = "suck"
author = "DCD"
mainprefix = "dcd"
folder_optionals = true
version = "1.0.02"
sig_version = 3
reuse_private_key = true

files = [
    "mod.cpp",
]

optionals = ["tracers", "particles"]
